version: "3"

services:

  nifi:
    image: apache/nifi:latest
    ports:
      - "8443:8443" # https://localhost:8443/nifi
    environment:
      # set admin credentials 
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=admin123456789
    volumes:
      - ./input:/var/lib/input/data
      - ./NiFi/conf:/opt/nifi/nifi-current/conf
    depends_on:
      - cassandra1
  nifi-registry:
    image: apache/nifi-registry:latest
    ports:
      - "18080:18080"
    volumes: 
      - ./NiFi/nifi_registry/database:/opt/nifi-registry/nifi-registry-current/database 
      - ./NiFi/nifi_registry/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
    depends_on:
      - nifi

  cassandra1:
    image: cassandra:latest
    container_name: cassandra-node-1
    volumes:
      - ./cassandra/data1:/var/lib/cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_CLUSTER_NAME=Raw Storage Cluster
      - CASSANDRA_DC=se1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch

  cassandra-cqlsh: # docker exec -it cassandra-cqlsh cqlsh cassandra1
    image: cassandra:latest
    container_name: cassandra-cqlsh
    depends_on:
      - cassandra1
    volumes:
      - ./cassandra/cassandra_schema.cql:/schema.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra1 -f /schema.cql && tail -F anything" #Hostname = cassandra1
    tty: true

  flink-jobmanager:
    image: flink:latest
    volumes:
      - ./flink/jobs:/home/flink/jobs
    ports:
      - "8085:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
  flink-taskmanager:
    image: flink:latest
    depends_on:
      - flink-jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2

  flink-jobmanager-ml:
    image: flink:latest
    volumes:
      - ./flink/jobs:/home/flink/jobs
    ports:
      - "8086:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager-ml
  flink-taskmanager-ml:
    image: flink:latest
    depends_on:
      - flink-jobmanager-ml
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager-ml
        taskmanager.numberOfTaskSlots: 2
 
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - ./kafka/zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    build: ./kafka/
    image: pipeline_kakfka
    ports:
      - '9092:9092'
    volumes:
    - ./kafka/data:/bitnami/kafka
    - ./kafka/scripts:/home/kafka-scripts
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - zookeeper



    
       